### ISSUE TITLE
3.1.0: pytest is failing on hosts without ipv6

### ISSUE THREAD

**Issue by kloczek** [jaraco/portend#15]
I'm trying to package your module as an rpm package. So I'm using the typical build, install and test cycle used on building packages from non-root account.
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Looks like pytest is failing on hosts without ipv6:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-portend-3.1.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-portend-3.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/portend-3.1.0, configfile: pytest.ini
plugins: shutil-1.7.0, virtualenv-1.7.0, mock-3.6.1, cov-2.12.1, anyio-3.3.4, forked-1.3.0, xdist-2.3.0, flaky-3.7.0, tornasync-0.6.0.post2, console-scripts-1.2.0, trio-0.7.0, timeout-2.0.1, asyncio-0.16.0, hypothesis-6.27.0, freezegun-0.4.2, flake8-1.0.7
collected 20 items

portend.py F...FF                                                                                                                                                    [ 30%]
test_portend.py .E.F.F.E.E.E.E                                                                                                                                       [100%]

================================================================================== ERRORS ==================================================================================
_____________________________________________ ERROR at setup of TestChecker.test_check_port_listening[AddressFamily.AF_INET6] ______________________________________________

request = <SubRequest 'listening_addr' for <Function test_check_port_listening[AddressFamily.AF_INET6]>>

    @pytest.fixture(**build_addr_infos())
    def listening_addr(request):
        af, socktype, proto, canonname, sa = request.param
>       sock = socket.socket(af, socktype, proto)

test_portend.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET6: 10>, type = <SocketKind.SOCK_STREAM: 1>, proto = 6
fileno = None

    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
        if fileno is None:
            if family == -1:
                family = AF_INET
            if type == -1:
                type = SOCK_STREAM
            if proto == -1:
                proto = 0
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 97] Address family not supported by protocol

/usr/lib64/python3.8/socket.py:231: OSError
_______________________________________________ ERROR at setup of TestChecker.test_free_with_timeout[AddressFamily.AF_INET6] _______________________________________________

request = <SubRequest 'listening_addr' for <Function test_free_with_timeout[AddressFamily.AF_INET6]>>

    @pytest.fixture(**build_addr_infos())
    def listening_addr(request):
        af, socktype, proto, canonname, sa = request.param
>       sock = socket.socket(af, socktype, proto)

test_portend.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET6: 10>, type = <SocketKind.SOCK_STREAM: 1>, proto = 6
fileno = None

    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
        if fileno is None:
            if family == -1:
                family = AF_INET
            if type == -1:
                type = SOCK_STREAM
            if proto == -1:
                proto = 0
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 97] Address family not supported by protocol

/usr/lib64/python3.8/socket.py:231: OSError
________________________________________ ERROR at setup of TestChecker.test_occupied_with_immediate_timeout[AddressFamily.AF_INET6] ________________________________________

request = <SubRequest 'listening_addr' for <Function test_occupied_with_immediate_timeout[AddressFamily.AF_INET6]>>

    @pytest.fixture(**build_addr_infos())
    def listening_addr(request):
        af, socktype, proto, canonname, sa = request.param
>       sock = socket.socket(af, socktype, proto)

test_portend.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET6: 10>, type = <SocketKind.SOCK_STREAM: 1>, proto = 6
fileno = None

    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
        if fileno is None:
            if family == -1:
                family = AF_INET
            if type == -1:
                type = SOCK_STREAM
            if proto == -1:
                proto = 0
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 97] Address family not supported by protocol

/usr/lib64/python3.8/socket.py:231: OSError
___________________________________________________________ ERROR at setup of test_main[AddressFamily.AF_INET6] ____________________________________________________________

request = <SubRequest 'listening_addr' for <Function test_main[AddressFamily.AF_INET6]>>

    @pytest.fixture(**build_addr_infos())
    def listening_addr(request):
        af, socktype, proto, canonname, sa = request.param
>       sock = socket.socket(af, socktype, proto)

test_portend.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET6: 10>, type = <SocketKind.SOCK_STREAM: 1>, proto = 6
fileno = None

    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
        if fileno is None:
            if family == -1:
                family = AF_INET
            if type == -1:
                type = SOCK_STREAM
            if proto == -1:
                proto = 0
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 97] Address family not supported by protocol

/usr/lib64/python3.8/socket.py:231: OSError
_______________________________________________________ ERROR at setup of test_main_timeout[AddressFamily.AF_INET6] ________________________________________________________

request = <SubRequest 'listening_addr' for <Function test_main_timeout[AddressFamily.AF_INET6]>>

    @pytest.fixture(**build_addr_infos())
    def listening_addr(request):
        af, socktype, proto, canonname, sa = request.param
>       sock = socket.socket(af, socktype, proto)

test_portend.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET6: 10>, type = <SocketKind.SOCK_STREAM: 1>, proto = 6
fileno = None

    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
        if fileno is None:
            if family == -1:
                family = AF_INET
            if type == -1:
                type = SOCK_STREAM
            if proto == -1:
                proto = 0
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 97] Address family not supported by protocol

/usr/lib64/python3.8/socket.py:231: OSError
================================================================================= FAILURES =================================================================================
__________________________________________________________________ [doctest] portend.Checker.assert_free ___________________________________________________________________
045
046         Assert that the given addr is free
047         in that all attempts to connect fail within the timeout
048         or raise a PortNotFree exception.
049
050         >>> free_port = find_available_local_port()
051
052         >>> Checker().assert_free('localhost', free_port)
UNEXPECTED EXCEPTION: OSError(97, 'Address family not supported by protocol')
Traceback (most recent call last):
  File "/usr/lib64/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest portend.Checker.assert_free[1]>", line 1, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 71, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 74, in _connect
    s = socket.socket(af, socktype, proto)
  File "/usr/lib64/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py:52: UnexpectedException
__________________________________________________________________________ [doctest] portend.free __________________________________________________________________________
099
100     Wait for the specified port to become free (dropping or rejecting
101     requests). Return when the port is free or raise a Timeout if timeout has
102     elapsed.
103
104     Timeout may be specified in seconds or as a timedelta.
105     If timeout is None or ∞, the routine will run indefinitely.
106
107     >>> free('localhost', find_available_local_port())
UNEXPECTED EXCEPTION: OSError(97, 'Address family not supported by protocol')
Traceback (most recent call last):
  File "/usr/lib64/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest portend.free[0]>", line 1, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 122, in free
    Checker(timeout=0.1).assert_free(host, port)
  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 71, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 74, in _connect
    s = socket.socket(af, socktype, proto)
  File "/usr/lib64/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py:107: UnexpectedException
________________________________________________________________________ [doctest] portend.occupied ________________________________________________________________________
132
133     Wait for the specified port to become occupied (accepting requests).
134     Return when the port is occupied or raise a Timeout if timeout has
135     elapsed.
136
137     Timeout may be specified in seconds or as a timedelta.
138     If timeout is None or ∞, the routine will run indefinitely.
139
140     >>> occupied('localhost', find_available_local_port(), .1)
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,14 @@
     Traceback (most recent call last):
    -...
    -Timeout: Port ... not bound on localhost.
    +  File "/usr/lib64/python3.8/doctest.py", line 1336, in __run
    +    exec(compile(example.source, filename, "single",
    +  File "<doctest portend.occupied[0]>", line 1, in <module>
    +    occupied('localhost', find_available_local_port(), .1)
    +  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 157, in occupied
    +    Checker(timeout=0.5).assert_free(host, port)
    +  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 71, in assert_free
    +    list(itertools.starmap(self._connect, info))
    +  File "/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py", line 74, in _connect
    +    s = socket.socket(af, socktype, proto)
    +  File "/usr/lib64/python3.8/socket.py", line 231, in __init__
    +    _socket.socket.__init__(self, family, type, proto, fileno)
    +OSError: [Errno 97] Address family not supported by protocol

/home/tkloczko/rpmbuild/BUILD/portend-3.1.0/portend.py:140: DocTestFailure
_____________________________________________________ TestChecker.test_check_port_nonlistening[AddressFamily.AF_INET6] _____________________________________________________

self = <test_portend.TestChecker object at 0x7f8ae2dff430>, nonlistening_addr = ('::', 56509, 0, 0)

    def test_check_port_nonlistening(self, nonlistening_addr):
>       portend.Checker().assert_free(nonlistening_addr)

test_portend.py:61:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
portend.py:71: in assert_free
    list(itertools.starmap(self._connect, info))
portend.py:74: in _connect
    s = socket.socket(af, socktype, proto)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET6: 10>, type = <SocketKind.SOCK_STREAM: 1>, proto = 6
fileno = None

    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
        if fileno is None:
            if family == -1:
                family = AF_INET
            if type == -1:
                type = SOCK_STREAM
            if proto == -1:
                proto = 0
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 97] Address family not supported by protocol

/usr/lib64/python3.8/socket.py:231: OSError
___________________________________________________ TestChecker.test_free_with_immediate_timeout[AddressFamily.AF_INET6] ___________________________________________________

self = <test_portend.TestChecker object at 0x7f8ae2dc5340>, nonlistening_addr = ('::', 56509, 0, 0), immediate_timeout = None

    def test_free_with_immediate_timeout(self, nonlistening_addr, immediate_timeout):
        host, port = nonlistening_addr[:2]
>       portend.free(host, port, timeout=1.0)

test_portend.py:65:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
portend.py:122: in free
    Checker(timeout=0.1).assert_free(host, port)
portend.py:71: in assert_free
    list(itertools.starmap(self._connect, info))
portend.py:74: in _connect
    s = socket.socket(af, socktype, proto)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET6: 10>, type = <SocketKind.SOCK_STREAM: 1>, proto = 6
fileno = None

    def __init__(self, family=-1, type=-1, proto=-1, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
        if fileno is None:
            if family == -1:
                family = AF_INET
            if type == -1:
                type = SOCK_STREAM
            if proto == -1:
                proto = 0
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 97] Address family not supported by protocol

/usr/lib64/python3.8/socket.py:231: OSError
========================================================================= short test summary info ==========================================================================
ERROR test_portend.py::TestChecker::test_check_port_listening[AddressFamily.AF_INET6] - OSError: [Errno 97] Address family not supported by protocol
ERROR test_portend.py::TestChecker::test_free_with_timeout[AddressFamily.AF_INET6] - OSError: [Errno 97] Address family not supported by protocol
ERROR test_portend.py::TestChecker::test_occupied_with_immediate_timeout[AddressFamily.AF_INET6] - OSError: [Errno 97] Address family not supported by protocol
ERROR test_portend.py::test_main[AddressFamily.AF_INET6] - OSError: [Errno 97] Address family not supported by protocol
ERROR test_portend.py::test_main_timeout[AddressFamily.AF_INET6] - OSError: [Errno 97] Address family not supported by protocol
FAILED portend.py::portend.Checker.assert_free
FAILED portend.py::portend.free
FAILED portend.py::portend.occupied
FAILED test_portend.py::TestChecker::test_check_port_nonlistening[AddressFamily.AF_INET6] - OSError: [Errno 97] Address family not supported by protocol
FAILED test_portend.py::TestChecker::test_free_with_immediate_timeout[AddressFamily.AF_INET6] - OSError: [Errno 97] Address family not supported by protocol
================================================================== 5 failed, 10 passed, 5 errors in 0.93s ==================================================================
```

**Comment by jaraco** [comment]
IPv6 was introduced in 1995. Maybe it's time to enable it?

You'll notice that the code base makes no reference to AF_INET6, suggesting to me that your OS is misconfigured. See #6 and #8 where I encountered environments where IPv6 was half-disabled. I suggest first making sure that `getaddrinfo` on that host for `AF_UNSPEC` is not returning infos with AF_INET6 family.

If you have a way for me to replicate your environment, such as with a Docker image, I might be able to investigate further.

**Comment by jaraco** [comment]
I'm not sure there's anything this project can do to help. 

I did try replicating the issue in a Docker container, but I get three tests failures in the container before the tests hang and have to be interrupted, and that's without tweaking IPv6 at all.

<details>

```
 portend main $ docker run -it -v @$(pwd):/src jaraco/multipy-tox bash -c 'cd src; export TOX_WORK_DIR=/tox; tox'
python create: /tox/python
python develop-inst: /src
python installed: attrs==22.1.0,black==22.10.0,build==0.9.0,click==8.1.3,coverage==6.5.0,docutils==0.19,filelock==3.8.0,flake8==4.0.1,iniconfig==1.1.1,jaraco.context==4.1.2,jaraco.functools==3.5.2,mccabe==0.6.1,more-itertools==9.0.0,mypy==0.990,mypy-extensions==0.4.3,packaging==21.3,pathspec==0.10.1,pep517==0.13.0,platformdirs==2.5.3,pluggy==1.0.0,-e git+gh://jaraco/portend@1f9e16ec32611b02e4e2a4518f0694df33e57d0a#egg=portend,pycodestyle==2.8.0,pyflakes==2.4.0,pyparsing==3.0.9,pytest==7.2.0,pytest-black==0.3.12,pytest-checkdocs==2.9.0,pytest-cov==4.0.0,pytest-enabler==1.3.0,pytest-flake8==1.1.1,pytest-mypy==0.10.1,pytz==2022.6,tempora==5.0.2,toml==0.10.2,typing_extensions==4.4.0
python run-test-pre: PYTHONHASHSEED='555350929'
python run-test: commands[0] | pytest
================================================================= test session starts ==================================================================
platform linux -- Python 3.11.0rc1, pytest-7.2.0, pluggy-1.0.0
cachedir: /tox/python/.pytest_cache
rootdir: /src, configfile: pytest.ini
plugins: black-0.3.12, cov-4.0.0, flake8-1.1.1, checkdocs-2.9.0, mypy-0.10.1, enabler-1.3.0
collected 32 items                                                                                                                                     

portend.py ..........                                                                                                                            [ 32%]
. .                                                                                                                                              [ 35%]
test_portend.py ....F.....F.F.^CERROR: got KeyboardInterrupt signal


======================================================================= FAILURES =======================================================================
______________________________________________________ TestChecker.test_check_port_listening[10] _______________________________________________________

self = <test_portend.TestChecker object at 0xffffa3eae210>, listening_addr = ('::', 47327, 0, 0)

    def test_check_port_listening(self, listening_addr):
>       with pytest.raises(portend.PortNotFree):
E       Failed: DID NOT RAISE <class 'portend.PortNotFree'>

test_portend.py:57: Failed
________________________________________________________ TestChecker.test_free_with_timeout[10] ________________________________________________________

self = <test_portend.TestChecker object at 0xffffa3eb09d0>, listening_addr = ('::', 47327, 0, 0)

    def test_free_with_timeout(self, listening_addr):
        host, port = listening_addr[:2]
>       with pytest.raises(portend.Timeout):
E       Failed: DID NOT RAISE <class 'portend.Timeout'>

test_portend.py:69: Failed
_________________________________________________ TestChecker.test_occupied_with_immediate_timeout[10] _________________________________________________

self = <test_portend.TestChecker object at 0xffffa3eb16d0>, listening_addr = ('::', 47327, 0, 0), immediate_timeout = None

    def test_occupied_with_immediate_timeout(self, listening_addr, immediate_timeout):
        host, port = listening_addr[:2]
>       portend.occupied(host, port, timeout=1.0)

test_portend.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

host = '::', port = 47327, timeout = 1.0

    def occupied(host, port, timeout=float('Inf')):
        """
        Wait for the specified port to become occupied (accepting requests).
        Return when the port is occupied or raise a Timeout if timeout has
        elapsed.
    
        Timeout may be specified in seconds or as a timedelta.
        If timeout is None or ∞, the routine will run indefinitely.
    
        >>> occupied('localhost', find_available_local_port(), .1)
        Traceback (most recent call last):
        ...
        Timeout: Port ... not bound on localhost.
    
        >>> occupied(None, None)
        Traceback (most recent call last):
        ...
        ValueError: Host values of '' or None are not allowed.
        """
        if not host:
            raise ValueError("Host values of '' or None are not allowed.")
    
        timer = timing.Timer(timeout)
    
        while True:
            try:
                Checker(timeout=0.5).assert_free(host, port)
>               if timer.expired():
E               TypeError: immediate_timeout.<locals>.<lambda>() takes 0 positional arguments but 1 was given

portend.py:158: TypeError
========================================================================= mypy =========================================================================
Success: no issues found in 3 source files
=============================================================== short test summary info ================================================================
FAILED test_portend.py::TestChecker::test_check_port_listening[10] - Failed: DID NOT RAISE <class 'portend.PortNotFree'>
FAILED test_portend.py::TestChecker::test_free_with_timeout[10] - Failed: DID NOT RAISE <class 'portend.Timeout'>
FAILED test_portend.py::TestChecker::test_occupied_with_immediate_timeout[10] - TypeError: immediate_timeout.<locals>.<lambda>() takes 0 positional arguments but 1 was given
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/tox/python/lib/python3.11/site-packages/coverage/sqldata.py:1106: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
============================================================ 3 failed, 22 passed in 25.63s =============================================================
_______________________________________________________________________ summary ________________________________________________________________________
ERROR:   python: keyboardinterrupt
```

</details>

I see that IPv6 still is unsupported on macOS in Docker, so I'm exploring other options such as podman, but right now, I'm out of time/energy on the issue.

I welcome more investigation in the failing environments and suggestions on how it could be more tolerant to these degraded environments. Right now, the tests only bind to families/protocols for [returned by getaddrinfo](https://github.com/jaraco/portend/blob/1f9e16ec32611b02e4e2a4518f0694df33e57d0a/test_portend.py#L20). I realize the request for a Docker recipe may not be the best fit here, because Docker itself has to virtualize interfaces in a way that might break assumptions of this project. I'd also be willing to investigate if we had a set of instructions to replicate against an install of a standard OS in a VM.
